moj-analytical-services/platform_user_guidance

index.Rmd

if last commit worked this PR shouldn't publish gh-pages

test commit for PR

---

03-deploying_shiny_app.Rmd

Added more details on how to install, save/exit in the nano text editor.
Tweaked some wording and fixed a little typo.

Tweaked Shiny app troubleshooting instructions

---

03-deploying_shiny_app.Rmd

I wanted to provide a reminder to refresh docker before trying to rebuild an app locally to make sure you are viewing the latest build.

Added note on refreshing docker before rebuilding app. Fixed spelling error.

---

03-using-github-in-rstudio.Rmd

Just changed a few things, mainly rewording some parts that I thought might be confusing. Also added link to the github training notes on dom1.

review of guidance

---

00-quick_start.Rmd
01-start.Rmd
08-SyOps.Rmd

Some style changes and clarification, mostly for 08-...

Suggested changes.

---

09-Annex.Rmd

Added a new bullet point about not losing files in messy storage systems (e.g. DOM1). Plus I fixed a couple of tiny errors.

Review of benefits of GitHub annex

---

03-using-github-in-rstudio.Rmd

Suggested additional step to the GitHub/RStudio part of the guidance that encourages code to be more open.
Also corrected the line of code that creates a branch.

Repo visibility decisions

---

01-start.Rmd

Revise the requirements on which IT people can access the MOJ Analytical Platform from.

Accessing the platform

---

09-SyOps.Rmd

Adjust AUP/SyOps

---

04-deploying_shiny_app.Rmd
05-deploying_static.Rmd

Add note that deploy.json needs to be on the master branch for the concourse scan to pick up the app repo.
Also some minor formatting - the numbered list wasn't rendering and hopefully the newline will fix it.

deploy.json needs to be on the master branch

---

10-Annex.Rmd

Add a description of data anonymisation and pseudonymisation

Add Data Minimisation to Annex

---

02-start.Rmd
10-acceptable-use-policy

Fix broken link to acceptable use policy.

Fix broken link

---

11-information_governance.Rmd

Update the link to the data movement form so that it points to a Microsoft form as opposed to a Google form. This should fix access issues for Quantum users (#66).

change dmf link to Microsoft form

---

05-deploying_shiny_app.Rmd
08-build_and_deploy.Rmd

Update guidance on deploying Shiny apps

---

11-information_governance.Rmd

Add an explicit section on data offshoring

Add 'data offshoring'

---

.circleci/config.yml

I've had a go at writing a `config.yml` for Circle CI. It seems to work but I'm no expert. If we're happy it works and want to move across, we can get rid of the Travis stuff.

Add config.yml for Circle CI deployment

---

.circleci/config.yml

Make sure we really add all the files

Bugfix .circleci/config.yml

---

10-acceptable-use-policy.Rmd

Clarify the AUP doesnt apply to apps

---

.circleci/config.yml
02-start.Rmd
10-acceptable-use-policy.Rmd
14-Annex.Rmd

- New Password Manager section
- Update link to best practice guidelines in section 10
- Update broken link in section 2

Add Password Manager section recommendation, update links section 10 

---

11-information_governance.Rmd

Updating the link to the data movement form, so it works with the approval workflow.

Update link to DMR

---

.gitignore
05-deploying_shiny_app.Rmd

Limited rewrite of the RShiny section to ensure consistency with the rest of the guidance and the GDS Style Guide.
There are no substantial changes to content.

Rewrite of the RShiny section

---

.gitignore
03-accessing_files_in_s3.Rmd
03-amazon_s3.Rmd

Substantial rewrite of the section on Amazon S3, including detailed instructions on how to upload and download files using various methods. Also adds references to information governance procedures that should be followed when uploading data to S3.

Rewrite the section on Amazon S3

---

03-amazon_s3.Rmd

Fixes failing build on master due to `reticulate` dependency for Python code chunks.

Fix Python dependency issue

---

04-using-github-with-the-platform.Rmd

Fixes #106 (cloning a repo for Jupyter/command-line users)

Add how to clone repo in terminal

---

11-information_governance.Rmd

Fix DPIA link

---

01-introduction.Rmd
03-amazon_s3.Rmd
05-deploying_shiny_app.Rmd
06-deploying_static.Rmd
14-Annex.Rmd

* Updates all instances of the old control panel URL
* Makes information on data sources non-type specific (do not make a distinction between warehouse and webapp data sources)
* Adds information on managing app users
* Fixes some list numbering
* Makes email addresses explicit

Update guidance to reflect new control panel

---

15-Appendix.Rmd

Instructions on how to fix the r-pillar error as a conda user.

How to fix r-pillar error

---

06-deploying_static.Rmd

updating static web deployment section

---

README.md

Thought this could be improved, in the course of looking at #125.
Feel free to add in the ??? @calumabarnett or just hit merge and simply update as part of #125

A bit more explanation of the CI/CD

---

03-amazon_s3.Rmd
README.md

I always feel a bit hazy on 'data sources' on AP, so am keen to write down a description of them. App data sources are particularly scant in the docs.
@isichei I've mentioned curated buckets twice - can you clarify if they are warehouse data sources or not?

Add more detail on data sources

---

.circleci/config.yml
redirect.html

Replace all HTML files with redirect pages.

Enable redirection to the new user guidance
